/**
 * The primitives every screen is built from, ported from Helix's
 * `components.tsx`, `primitives.tsx` and `selection-controls.tsx` as the first
 * screens need them. Helix keeps three files because it has sixty components;
 * Gital has five.
 */

import { useRef, type ReactNode } from "react";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions, type StyleProp, type TextStyle } from "react-native";
import { useScrollToTop, useSegments } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { interactionSurface } from "./interaction";
import { shouldUseWideGutter } from "./responsive";
import {
  alpha,
  borderWidth,
  contentWidth,
  density,
  font,
  navigationInset,
  offset,
  pressDepth,
  proseLeading,
  radius,
  sectionMark,
  spacing,
  type,
  useTheme,
  type ContentWidth,
  type Palette,
} from "./theme";

/**
 * Every routed surface renders one Screen, which owns what a screen never
 * restates: the gutter, the top inset, the clearance under the floating tab
 * bar, and a centred column capped by a named width (`docs/UI.md` section 3).
 */
export function Screen({
  children,
  title,
  width: widthName = "form",
}: {
  children?: ReactNode;
  title?: string;
  width?: ContentWidth;
}) {
  const { palette } = useTheme();
  const insets = useSafeAreaInsets();
  const { width } = useWindowDimensions();
  // A root route — a modal, sign-in — has no bar under it. Widened: typed
  // routes are generated by `expo start`, so CI types the segments differently.
  const inTabs = (useSegments() as string[])[0] === "(tabs)";
  // Pressing the tab you are on returns its screen to the top.
  const scrollRef = useRef<ScrollView>(null);
  useScrollToTop(scrollRef);
  const gutter = shouldUseWideGutter(width) ? spacing.xxl : spacing.lg;
  const bottomPad = inTabs
    ? navigationInset({ bottomInset: insets.bottom, isWeb: Platform.OS === "web" }).bottom
    : Math.max(insets.bottom, spacing.lg) + spacing.md;
  const topPad = Math.max(insets.top, spacing.lg);

  return (
    <View style={{ flex: 1, backgroundColor: palette.background }}>
      {/* Content passes under the status bar; without a band painted over it a
          row's label runs straight through the clock. */}
      {insets.top > 0 ? (
        <View
          pointerEvents="none"
          accessible={false}
          style={[styles.statusBand, { height: insets.top, backgroundColor: palette.background }]}
        />
      ) : null}
      <ScrollView
        ref={scrollRef}
        automaticallyAdjustContentInsets={false}
        contentContainerStyle={{
          paddingHorizontal: gutter,
          paddingTop: topPad,
          paddingBottom: bottomPad,
          width: "100%",
          maxWidth: contentWidth[widthName],
          alignSelf: "center",
          flexGrow: 1,
        }}
      >
        {title != null ? (
          <Text
            accessibilityRole="header"
            aria-level={1}
            style={[type.title, { color: palette.textStrong, marginBottom: spacing.lg }]}
          >
            {title}
          </Text>
        ) : null}
        {children}
      </ScrollView>
    </View>
  );
}

export function Card({ children }: { children: ReactNode }) {
  const { palette } = useTheme();
  return (
    <View
      style={{
        backgroundColor: palette.surface,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: palette.border + alpha.edge,
        borderRadius: radius.lg,
        padding: density.list.cardPadding,
        marginBottom: spacing.md,
        overflow: "hidden",
        borderCurve: "continuous",
      }}
    >
      {children}
    </View>
  );
}

/** A section owns both sides of itself, because it separates two groups. */
export function SectionHeader({ children }: { children: ReactNode }) {
  const { palette } = useTheme();
  return (
    <View style={{ marginTop: density.list.sectionGap, marginBottom: spacing.sm, flexDirection: "row", alignItems: "center", gap: spacing.md }}>
      <View
        accessible={false}
        style={{ width: sectionMark.width, height: sectionMark.height, borderRadius: sectionMark.radius, backgroundColor: palette.primary }}
      />
      <Text
        accessibilityRole="header"
        aria-level={2}
        style={[type.sectionTitle, { color: palette.textStrong, flex: 1, minWidth: 0 }]}
      >
        {children}
      </Text>
    </View>
  );
}

export function Body({ children, muted, style }: { children: ReactNode; muted?: boolean; style?: StyleProp<TextStyle> }) {
  const { palette } = useTheme();
  return (
    <Text
      style={[
        type.body,
        // Prose, and the only role given a line box — on web, where the `font`
        // shorthand would otherwise leave it at ~1.21.
        Platform.OS === "web" && { lineHeight: Math.round(type.body.fontSize * proseLeading) },
        { color: muted ? palette.textSecondary : palette.text },
        style,
      ]}
    >
      {children}
    </Text>
  );
}

/**
 * One tile, one answer. The shell will not let a caller change the box when
 * it is chosen — a thickening ring or a bolder label re-wraps the row — so
 * colour, fill and the accessible state carry the choice.
 */
export function ChoiceTile({
  label,
  description,
  selected,
  onPress,
  disabled = false,
  children,
  layout = "stack",
  minHeight,
  basis,
  surface,
}: {
  label: string;
  description?: string;
  selected: boolean;
  onPress: () => void;
  disabled?: boolean;
  children?: ReactNode;
  /** `stack` puts the content over the label; `row` beside it. */
  layout?: "stack" | "row";
  minHeight: number;
  /** `flexBasis` for a wrapping grid; omit to share the row evenly. */
  basis?: `${number}%`;
  /** Draw in a palette the app is not wearing — the appearance card previews its choices. */
  surface?: Palette;
}) {
  const { palette } = useTheme();
  const p = surface ?? palette;
  const row = layout === "row";
  return (
    <Pressable
      accessibilityRole="radio"
      accessibilityLabel={label}
      aria-checked={selected}
      accessibilityState={{ checked: selected, disabled }}
      disabled={disabled}
      onPress={onPress}
      style={(state) => ({
        flexGrow: 1,
        flexBasis: basis ?? 0,
        minWidth: 0,
        minHeight,
        padding: spacing.sm,
        gap: row ? spacing.md : spacing.xs,
        flexDirection: row ? "row" : "column",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: radius.md,
        borderWidth: borderWidth.selected,
        borderColor: disabled ? p.controlBorder : selected ? p.primary : p.border + alpha.tileEdge,
        // Disabled is said in colour, never by fading: a refused control still explains itself.
        ...interactionSurface(p, state, {
          base: disabled ? p.surfaceAlt : selected ? p.primary + alpha.selectedTint : p.surface,
          enabled: !disabled,
        }),
        transform: [{ translateY: state.pressed && !disabled ? pressDepth : 0 }],
      })}
    >
      {children}
      <View style={row ? { flex: 1, minWidth: 0, justifyContent: "center" } : { minWidth: 0 }}>
        <Text
          style={[
            description ? type.body : type.small,
            {
              color: selected ? p.textStrong : p.text,
              fontFamily: font.semibold,
              textAlign: row ? "left" : "center",
              flexShrink: 1,
            },
          ]}
        >
          {label}
        </Text>
        {description ? (
          <Text style={[type.small, { color: p.textSecondary, marginTop: offset.tuck, textAlign: row ? "left" : "center", flexShrink: 1 }]}>
            {description}
          </Text>
        ) : null}
      </View>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  statusBand: { position: "absolute", top: 0, left: 0, right: 0, zIndex: 2 },
});

